#dfile: C:\Users\admin\notebooks\template_data\template_data_scd_20251009.txt
dfile: /home/jgeng/notebooks/template_data_oogapc_v2/template_data_oogapc_v2_20251031.txt.fastfvoo
NFold: 50
distType: 4
SCBand: 5
Ks: 2500
WFD: 1
leakDist: 30
colDate: 2
colSym: 1
colYNames: [FGAP,FOC2,FGAP2,ccF1D,ccF2D,ooFD2]
colXNames: [FMC,FOM,GAP,OO_1, OO_1t2, OO_1t3, OO_1t4, OO_1t5, OO_1t6, OO_1t7, OO_1t8, OO_1t9, OO_1t10, OO_1t11, OO_1t12, OO_1t13, OO_1t14, OO_1t15, OO_1t16, OO_1t17, OO_1t18, OO_1t19, OO_1t20]
wgts: [8,8,2,1,  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
#wgts: [8,8,2,0, 0,0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
