library(dplyr)
library(lubridate)
#library(DT)
#library(doParallel)
#library(tidyr)
#library(purrr)
# library(forecast)
library(tseries)
library(moments)


source("~/myRFuncs/printSharpeRatio.R")
source("~/myRFuncs/myMaxDrawdown.R")
source("~/myRFuncs/OLS.R")
source("~/myRFuncs/MS.R")
source("~/myRFuncs/turnover.R")
source("~/myRFuncs/myMaxShp2.R")
source("~/myRFuncs/srmdd_central2.R")
source("~/myRFuncs/mdd.R")
source("~/myRFuncs/OLSIntra.R")
source("~/myRFuncs/printSharpeRatioIntra.R")
source("~/myRFuncs/MSIntra.R")
source("~/myRFuncs/cvfcst1.R")
source("~/myRFuncs/knncv_fcst.R")
source("~/myRFuncs/knncv_ebg_fcst.R")
source("~/myRFuncs/DecilePlot.R")
source("~/myRFuncs/DecilePlot20.R")
